title: Innovation Lab
description: Innovation Lab, Universidad Galileo.

url: "localhost:4000"
baseurl: ""

markdown: kramdown
highlighter: rouge

navigation:
 - title: Home
   url: /index.html
 - title: Staff
   url: /staff.html
 - title: Proyectos
   url: /proyectos.html
 - title: Presentaciones
   url: /presentaciones.html
 - title: Talleres
   url: /talleres.html

social:
   github: InnovationLabUG
