title: Laboratorio de Innovacion
description: Laboratorio de Innovacion, Universidad Galileo.

url: "https://InnovationLabUGProjects.github.io/"
baseurl: ""

markdown: kramdown
highlighter: rouge

navigation:
 - title: Home
   url: /index.html
 - title: Staff
   url: /staf.html
 - title: Proyectos
   url: /proyectos.html

social:
   github: InnovationLabUGProjects
